theme: jekyll-theme-minimal
name: Calcium
markdown: kramdown
highlighter: rouge
default_lang: csharp
permalink: /blog/:year/:month/:day/:title
encoding: utf-8
repository: CalciumFramework/CalciumFramework.github.io